myproject/animals/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField, FloatField



class AddForm(FlaskForm):

    animalID = IntegerField('ID of Animal:')
    startWeight = FloatField('Start Weight of Animal: ')
    w1 = FloatField('Weight at first weigh in: ')
    w2 = FloatField('Weight at second weigh in: ')
    w3 = FloatField('Weight at third weigh in: ')
    w4 = FloatField('Weight at fourth weigh in: ')
    finalWeight = FloatField('Weight at Final Weigh In')
    motherID = IntegerField('ID of Mother')
    fatherID = IntegerField('ID of Father')
    diet = StringField('Diet Type of Animal')
    ch4_daily_mean = FloatField('Daily Mean of Methane Produced')
    feedEfficiency = FloatField('Feed Efficiancy of Animal')
    waterEfficieny = FloatField('Water Efficiancy of Animal')
    submit = SubmitField('Add Animal')

class DelForm(FlaskForm):

    animalID = IntegerField('Id Number of Animal to Remove:')
    submit = SubmitField('Remove Animal')

myproject/animals/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Animal
from myproject.animals.forms import AddForm, DelForm



animals_blueprint = Blueprint('animals', __name__,
                                template_folder='templates/animals')


@animals_blueprint.route('/add',methods =['GET','POST'])
def add():
    form = AddForm()

    if form.validate_on_submit():
        animalID = form.animalID.data
        startWeight = form.startWeight.data
        w1 = form.w1.data
        w2 = form.w2.data
        w3 = form.w3.data
        w4 = form.w4.data
        finalWeight = form.finalWeight.data
        motherID = form.motherID.data
        fatherID = form.fatherID.data
        diet = form.diet.data
        ch4_daily_mean = form.ch4_daily_mean.data
        feedEfficiency = form.feedEfficiency.data
        waterEfficieny = form.waterEfficieny.data



        # Add new Animal to database
        new_animal = Animal(animalID,startWeight,w1,w2,w3,w4,finalWeight,
                        motherID,fatherID,diet,ch4_daily_mean,feedEfficiency,waterEfficieny)
        db.session.add(new_animal)
        db.session.commit()

        return redirect(url_for('animals.list'))

    return render_template('add.html',form=form)


@animals_blueprint.route('/list')
def list():
    # Grab a list of animals from database.
    animals = Animal.query.all()
    return render_template('list.html', animals=animals)

#DELETE ANIMAL FROM DATABASE
@animals_blueprint.route('/delete',methods =['GET','POST'])
def delete():

    form = DelForm()

    if form.validate_on_submit():
        animalID = form.animalID.data
        animal = Animal.query.get(animalID)
        db.session.delete(animal)
        db.session.commit()

        return redirect(url_for('animals.list'))
    return render_template('delete.html',form=form)


@animals_blueprint.route('/graph/<input_data>')
def graph(input_data):
    

    return render_template('graph.html')


    

    

myproject/animals/templates/animals/add.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <form method="POST">
      {# This hidden_tag is a CSRF security feature. #}
      {{ form.hidden_tag() }}
      {{ form.animalID.label }} {{ form.animalID() }}
      <br>
      {{ form.startWeight.label }} {{ form.startWeight() }}
      <br>
      {{ form.w1.label }} {{ form.w1() }}
      <br>
      {{ form.w2.label }} {{ form.w2() }}
      <br>
      {{ form.w3.label }} {{ form.w3() }}
      <br>
      {{ form.w4.label }} {{ form.w4() }}
      <br>
      {{ form.finalWeight.label }} {{ form.finalWeight() }}
      <br>
      {{ form.motherID.label }} {{ form.motherID() }}
      <br>
      {{ form.fatherID.label }} {{ form.fatherID() }}
      <br>
      {{ form.diet.label }} {{ form.diet() }}
      <br>
      {{ form.ch4_daily_mean.label }} {{ form.ch4_daily_mean() }}
      <br>
      {{ form.feedEfficiency.label }} {{ form.feedEfficiency() }}
      <br>
      {{ form.waterEfficieny.label }} {{ form.waterEfficieny() }}
      <br>
      {{ form.submit() }}
  </form>
</div>
{% endblock %}

myproject/animals/templates/animals/delete.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron">

    <form  method="post">
        
    {{form.hidden_tag()}}
    {{form.animalID.label}}{{form.animalID}}
    {{form.submit()}}


    </form>
</div>

{% endblock  %}

myproject/animals/templates/animals/graph.html
{% extends 'base.html' %}

{% block content %}

{% endblock  %}

myproject/animals/templates/animals/list.html
{% extends 'base.html' %}

{% block content %}
<div class="row text-center">
<div class="col-md-12">
  <h1 class="display-4">Here Are All our Animal Profiles</h1>
</div>
</div>

  <div class="container">
    
    <div class="card-deck mb-3 text-center">
        {% if animals %} 
        {% for animal in animals  %}

        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card mb-4 shadow-sm">
            <div class="card-body">
              <h1 class="card-title pricing-card-title">ID: {{animal.animalID}} </h1>
              <ul class="list-unstyled mt-3 mb-4">
                <li><b>Start Weight :</b> {{animal.startWeight}}</li>
                <li><b>First Weigh In: </b> {{animal.w1}}</li>
                <li><b>Second Weigh In: </b>{{animal.w2}}</li>
                <li><b>Third Weigh In: </b>{{animal.w3}}</li>
                <li><b>Fourth Weigh In: </b>{{animal.w4}}</li>
                <li><b>Final Weight: </b>{{animal.finalWeight}}</li>
                <li><b>Mother ID: </b>{{animal.motherID}}</li>
                <li><b>Father ID: </b>{{animal.fatherID}}</li>
                <li><b>Diet: </b>{{animal.diet}}</li>
                <li><b>Daily Methane Mean: </b>{{animal.ch4_daily_mean}}</li>
                <li><b>Feed Efficiency: </b>{{animal.feedEfficiency}}</li>
                <li><b>Water Efficiency: </b>{{animal.waterEfficieny}}</li>
                <a class="nav-item nav-link" href="{{ url_for('animals.graph' , input_data=animal.animalID ) }}">Graph For Animal</a>
                
              </ul>
            </div>
          </div>
        </div>
      

        {%  endfor %}

    {% else %}
          <div class="col-md-12"></div>
          <p>No Animals available</p>
    {% endif %}
      </div>

    </div>


{% endblock  %}