myproject/models.py
#MODELS.PY
# set up the db inside the __init__.py
from myproject import db

class Animal(db.Model):

    __tablename__ = 'animals'
    animalID = db.Column(db.Integer,primary_key = True)
    startWeight = db.Column(db.Float)
    w1 = db.Column(db.Float)
    w2 = db.Column(db.Float)
    w3 = db.Column(db.Float)
    w4 = db.Column(db.Float)
    finalWeight = db.Column(db.Float)
    motherID = db.Column(db.Integer)
    fatherID = db.Column(db.Integer)
    diet = db.Column(db.Text)
    ch4_daily_mean = db.Column(db.Float)
    feedEfficiency = db.Column(db.Float)
    waterEfficieny = db.Column(db.Float)

    def __init__(self,animalID,startWeight,w1,w2,w3,w4,finalWeight,
    motherID,fatherID,diet,ch4_daily_mean,feedEfficiency,waterEfficieny):
        self.animalID = animalID
        self.startWeight = startWeight
        self.w1 = w1
        self.w2 = w2
        self.w3 = w3
        self.w4 = animalID
        self.finalWeight = finalWeight
        self.motherID = motherID
        self.fatherID = fatherID
        self.diet = diet
        self.ch4_daily_mean = ch4_daily_mean
        self.feedEfficiency = feedEfficiency
        self.waterEfficieny = waterEfficieny

    def __repr__(self):
        
        return self
        

myproject/animals/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField, FloatField



class AddForm(FlaskForm):

    animalID = IntegerField('ID of Animal:')
    startWeight = FloatField('Start Weight of Animal: ')
    w1 = FloatField('Weight at first weigh in: ')
    w2 = FloatField('Weight at second weigh in: ')
    w3 = FloatField('Weight at third weigh in: ')
    w4 = FloatField('Weight at fourth weigh in: ')
    finalWeight = FloatField('Weight at Final Weigh In')
    motherID = IntegerField('ID of Mother')
    fatherID = IntegerField('ID of Father')
    diet = StringField('Diet Type of Animal')
    ch4_daily_mean = FloatField('Daily Mean of Methane Produced')
    feedEfficiency = FloatField('Feed Efficiancy of Animal')
    waterEfficieny = FloatField('Water Efficiancy of Animal')
    submit = SubmitField('Add Animal')

class DelForm(FlaskForm):

    animalID = IntegerField('Id Number of Animal to Remove:')
    submit = SubmitField('Remove Animal')

myproject/__init__.py
# __init__.py

import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)

app.config['SECRET_KEY'] = 'mysecretkey'
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' +os.path.join(basedir,'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)

from myproject.animals.views import animals_blueprint
app.register_blueprint(animals_blueprint, url_prefix='/animals')

myproject/animals/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Animal
from myproject.animals.forms import AddForm, DelForm



animals_blueprint = Blueprint('animals', __name__,
                                template_folder='templates/animals')


@animals_blueprint.route('/add',methods =['GET','POST'])
def add():
    form = AddForm()

    if form.validate_on_submit():
        animalID = form.animalID.data
        startWeight = form.startWeight.data
        w1 = form.w1.data
        w2 = form.w2.data
        w3 = form.w3.data
        w4 = form.w4.data
        finalWeight = form.finalWeight.data
        motherID = form.motherID.data
        fatherID = form.fatherID.data
        diet = form.diet.data
        ch4_daily_mean = form.ch4_daily_mean.data
        feedEfficiency = form.feedEfficiency.data
        waterEfficieny = form.waterEfficieny.data



        # Add new Animal to database
        new_animal = Animal(animalID,startWeight,w1,w2,w3,w4,finalWeight,
                        motherID,fatherID,diet,ch4_daily_mean,feedEfficiency,waterEfficieny)
        db.session.add(new_animal)
        db.session.commit()

        return redirect(url_for('animals.list'))

    return render_template('add.html',form=form)


@animals_blueprint.route('/list')
def list():
    # Grab a list of animals from database.
    animals = Animal.query.all()
    return render_template('list.html', animals=animals)

#DELETE ANIMAL FROM DATABASE
@animals_blueprint.route('/delete',methods =['GET','POST'])
def delete():

    form = DelForm()

    if form.validate_on_submit():
        animalID = form.animalID.data
        animal = Animal.query.get(animalID)
        db.session.delete(animal)
        db.session.commit()

        return redirect(url_for('animals.list'))
    return render_template('delete.html',form=form)


@animals_blueprint.route('/graph/<input_data>')
def graph(input_data):
    

    return render_template('graph.html')


    

    

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{{ url_for('index') }}">Home</a>
            <a class="nav-item nav-link" href="{{ url_for('animals.add') }}">Add Animal</a>
            <a class="nav-item nav-link" href="{{ url_for('animals.list') }}">List of Animal</a>
            <a class="nav-item nav-link" href="{{ url_for('animals.delete') }}">Delete Animal</a>
            

          </div>
    </nav>

    {% block content %}

    {% endblock %}
</body>
</html>

myproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron">

    <h1>Welcome</h1>
</div>
   
{% endblock  %}